[project]
name = "solver-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cplex",
    "cvxpy",
    "docplex",
    "linopy",
    "numpy",
    "pytest",
    "pytest-benchmark",
]

[tool.ruff.lint]
extend-select = ["I"]
